# Generated by Django 5.0.6 on 2025-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0002_meditationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='anxiety_range',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='depression_range',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sleep_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
