# Generated by Django 5.0.6 on 2025-12-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0003_assessment_anxiety_range_assessment_depression_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
