# Generated by Django 5.0.6 on 2026-01-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0006_assessment_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='stress_level',
            new_name='stress_score',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='responses',
            field=models.JSONField(default=dict),
        ),
    ]
